import { Outfit, Unbounded } from "next/font/google"; // Import both fonts
import "./globals.css";

const unbounded = Unbounded({
  subsets: ["latin"],
  variable: "--display-font",
});

const outfit = Outfit({
  variable: "--body-font",
  subsets: ["latin"]
});
export const metadata = {
  title: "Kris Furer | Web Development ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={` ${unbounded.variable} ${outfit.variable} `} lang="en">
      <body className="font-body">
        {children}
      </body>
    </html>
  );
}
